name: tdm
include:
  - path: nginx/docker-compose.yml
    project_directory: .
    env_file:
      - ./.env
      - ./.env.nginx
  - path: python/docker-compose.yml
    project_directory: .
    env_file:
      - ./.env
      - ./.env.python
  - path: psql/docker-compose.yml
    project_directory: .
    env_file:
      - ./.env.psql
  # - path: ./compose.commons.yml
