name: tdm
include:
  - path: ./nginx/compose.nginx.yml
    project_directory: .
    env_file:
      - ./.env
      - ./.nginx.env
  - path: ./python/compose.py.yml
    project_directory: .
    env_file:
      - ./.env
      - ./.python.env
  - path: ./psql/compose.psql.yml
    project_directory: .
    env_file:
