CREATE TABLE usr (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
    ,nick TEXT NOT NULL UNIQUE
    ,email TEXT NOT NULL UNIQUE
    ,passwd TEXT NOT NULL
    ,approved BOOLEAN NOT NULL DEFAULT FALSE
    ,code TEXT NOT NULL
    ,code_exp TIMESTAMP NOT NULL
);

CREATE TABLE log (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
    ,ip TEXT NOT NULL
    ,is_success BOOLEAN NOT NULL
    ,"action" TEXT NOT NULL
    ,timest TIMESTAMP NOT NULL
    ,"log" TEXT NOT NULL
);

