server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 301 https://$host$request_uri:${NGINX_HTTPS_OUTER_PORT};
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    root ${APP_MAIN_DIR};
    index index.html;

    server_name _;
    
    location /static {
        try_files $uri $uri/ =404;
    }

    location / {
        uwsgi_pass python:5000;
        include uwsgi_params;
    }
}