services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        - APP_MAIN_DIR=${APP_MAIN_DIR}
    volumes:
      - ./src:${APP_MAIN_DIR}/app:ro
      - doc_files:${DOC_FILES_DIR}:rw
    env_file:
      - ./.env.global
      - ./.env
      - ./.env.psql
      - ./.env.python
    depends_on:
      - psql
    expose:
      - 5000
volumes:
  doc_files:
