services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        - APP_MAIN_DIR=${APP_MAIN_DIR}
        - DOC_FILES_DIR=${DOC_FILES_DIR}
        - TEMP_FOLDER=${TEMP_FOLDER}
    volumes:
      - ./site:${APP_MAIN_DIR}/app:ro
      - ${DOC_FILES_DIR}:/var/doc_files:rw
    env_file:
      - ./.env
      - ./.psql.env
      - ./.python.env
    depends_on:
      - psql
    expose:
      - 5000
volumes:
  doc_files:
